name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS-ipa File Build
    runs-on: macos-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Update CocoaPods repo
        run: pod repo update
        working-directory: ios

      - name: Build iOS release (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Create Payload directory
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move Runner.app into Payload
        run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip IPA file
        run: zip -qq -r -9 EMT.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Rename IPA file using release tag
        run: mv EMT.ipa EMT-${{ github.ref_name }}.ipa
        working-directory: build/ios/iphoneos

      - name: Upload IPA to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/EMT-${{ github.ref_name }}.ipa
          tag: V1.0.0
          overwrite: true
          body: "This is the release IPA file for download and testing on iOS devices."
